apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: mangalodon
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: heftychonk/mangalodon-frontend
      context: src/frontend
      docker:
        dockerfile: Dockerfile
    - image: heftychonk/mangalodon-apiservice
      context: src/apiservice
      docker:
        dockerfile: Dockerfile
    - image: heftychonk/mangalodon-scrapeservice
      context: src/scrapeservice
      docker:
        dockerfile: Dockerfile
    - image: heftychonk/mangalodon-scrapescheduler
      context: src/scrapescheduler
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: mangalodon
        chartPath: charts/mangalodon
        namespace: mangalodon-dev
        createNamespace: true
        valuesFiles:
          - charts/mangalodon/values.yaml
        setValueTemplates:
          env: dev

          frontend.image.repository: "{{.IMAGE_REPO_heftychonk_mangalodon_frontend}}"
          frontend.image.tag: "{{.IMAGE_TAG_heftychonk_mangalodon_frontend}}"

          apiservice.image.repository: "{{.IMAGE_REPO_heftychonk_mangalodon_apiservice}}"
          apiservice.image.tag: "{{.IMAGE_TAG_heftychonk_mangalodon_apiservice}}"

          scrapeservice.image.repository: "{{.IMAGE_REPO_heftychonk_mangalodon_scrapeservice}}"
          scrapeservice.image.tag: "{{.IMAGE_TAG_heftychonk_mangalodon_scrapeservice}}"

          scrapescheduler.image.repository: "{{.IMAGE_REPO_heftychonk_mangalodon_scrapescheduler}}"
          scrapescheduler.image.tag: "{{.IMAGE_TAG_heftychonk_mangalodon_scrapescheduler}}"
          scrapescheduler.schedule: "* * * * *"

          postgres.replicas: 1

          rabbitmq.replicas: 1

          ingress.host: mangalodon-dev.com
