apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: mangalodon
build:
  artifacts:
    - image: mangalodon/frontend
      context: src/frontend
      docker:
        dockerfile: Dockerfile
    - image: mangalodon/apiservice
      context: src/apiservice
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: mangalodon
        chartPath: helm-chart
        valuesFiles:
          - helm-chart/values.yaml
        setValueTemplates:
          frontend.imageTag: "{{.DIGEST_HEX_741448960615_dkr_ecr_ap_southeast_1_amazonaws_com_mangalodon_frontend}}"
          apiservice.imageTag: "{{.DIGEST_HEX_741448960615_dkr_ecr_ap_southeast_1_amazonaws_com_mangalodon_apiservice}}"