apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.apiservice.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.apiservice.name }}
spec:
  {{- if not .Values.apiservice.autoscaling.enabled }}
  replicas: {{ .Values.apiservice.autoscaling.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      service: {{ .Values.apiservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: {{ .Values.apiservice.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.apiservice.name }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Values.apiservice.name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: {{ .Values.apiservice.image.repository | default .Values.images.repository }}:{{ .Values.apiservice.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.name }}-creds
                  key: rwUrl
            {{- if gt (int .Values.postgres.replicas) 1 }}
            - name: READ_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.name }}-creds
                  key: roUrl
            {{- end }}
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /api/health
              port: 3000
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /api/health
              port: 3000
          {{- with .Values.apiservice.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
{{- if .Values.apiservice.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.apiservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.apiservice.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.apiservice.name }}
  minReplicas: {{ .Values.apiservice.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiservice.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.apiservice.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiservice.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apiservice.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiservice.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.apiservice.name }}
spec:
  selector:
    service: {{ .Values.apiservice.name }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
