apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiservice.name }}
  namespace: {{ .Release.Namespace }}
# ---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultAuth
# metadata:
#   name: {{ .Values.apiservice.name }}
#   namespace: {{ .Release.Namespace }}
# spec:
#   vaultConnectionRef: {{ .Chart.Name }}
#   method: kubernetes
#   mount: {{ .Values.vault.kubernetesAuthMountPath }}
#   kubernetes:
#     role: {{ .Chart.Name }}-{{ .Values.apiservice.name }}-{{ .Values.env }}
#     serviceAccount: {{ .Values.apiservice.name }}
# ---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultStaticSecret
# metadata:
#   name: {{ .Values.apiservice.name }}-postgres-user
#   namespace: {{ .Release.Namespace }}
# spec:
#   vaultAuthRef: {{ .Values.apiservice.name }}
#   mount: {{ .Values.vault.kvEngine.mountPath }}
#   type: kv-{{ .Values.vault.kvEngine.version }}
#   path: {{ replace "<env>" .Values.env .Values.postgres.vaultSecretPath }}
#   refreshAfter: 10m
#   rolloutRestartTargets:
#     - name: {{ .Values.apiservice.name }}
#       kind: Deployment
#   destination:
#     name: {{ .Values.apiservice.name }}-postgres-user
#     create: true
#     overwrite: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.apiservice.name }}
spec:
  {{- if not .Values.apiservice.autoscaling.enabled }}
  replicas: {{ .Values.apiservice.autoscaling.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      service: {{ .Values.apiservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: {{ .Values.apiservice.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.apiservice.name }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Values.apiservice.name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: {{ .Values.apiservice.image.repository | default .Values.images.repository }}:{{ .Values.apiservice.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.name }}-user
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.name }}-user
                  key: password
            - name: DATABASE_URL
              value: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@{{ .Values.postgres.name }}-rw.{{ .Release.Namespace }}.svc:5432/{{ .Chart.Name }}?options=-c%20search_path%3D{{ .Values.postgres.schema }}"
            - name: READ_DATABASE_URL
              value: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@{{ .Values.postgres.name }}-ro.{{ .Release.Namespace }}.svc:5432/{{ .Chart.Name }}?options=-c%20search_path%3D{{ .Values.postgres.schema }}"
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /api/health
              port: 3000
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /api/health
              port: 3000
          {{- with .Values.apiservice.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
{{- if .Values.apiservice.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.apiservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.apiservice.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.apiservice.name }}
  minReplicas: {{ .Values.apiservice.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiservice.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.apiservice.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiservice.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apiservice.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiservice.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.apiservice.name }}
spec:
  selector:
    service: {{ .Values.apiservice.name }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
