apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.rabbitmq.name }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  persistence:
    storageClassName: {{ .Values.rabbitmq.storage.className }}
    storage: {{ .Values.rabbitmq.storage.size }}
  secretBackend:
    vault:
      role: {{ .Chart.Name }}-{{ .Values.rabbitmq.name }}-{{ .Values.env }}
      annotations:
        vault.hashicorp.com/service: {{ .Values.vault.server }}
        vault.hashicorp.com/tls-secret: {{ .Chart.Name }}-vault-ca
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/template-static-secret-render-interval: "5m"
      defaultUserPath: {{ .Values.vault.kvEngine.mountPath }}{{ ternary "/data/" "/" (eq .Values.vault.kvEngine.version "v2") }}{{ replace "<env>" .Values.env .Values.rabbitmq.vaultSecretPath.defaultUser }}
    # TODO: add mTLS by cert-manager