apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scrapeservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.scrapeservice.name }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ .Values.scrapeservice.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Values.scrapeservice.name }}
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 600
    backoffLimit: 3
    template:
      spec:
        serviceAccountName: {{ .Values.scrapeservice.name }}
        containers:
          - name: {{ .Values.scrapeservice.name }}
            image: {{ .Values.scrapeservice.image.repository | default .Values.images.repository }}:{{ .Values.scrapeservice.image.tag }}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              privileged: false
              readOnlyRootFilesystem: true
            env:
              - name: RABBITMQ_URL
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.rabbitmq.name }}-creds
                    key: host
              - name: RABBITMQ_QUEUE
                value: {{ .Values.rabbitmq.queue.name }}
            {{- with .Values.scrapeservice.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        restartPolicy: Never
  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  rollout:
    strategy: gradual
    propagationPolicy: background
  scalingStrategy:
    strategy: eager
  triggers:
    - type: rabbitmq
      metadata:
        mode: QueueLength
        queueName: {{ .Values.rabbitmq.queue.name }}
        value: "1"
        unsafeSsl: "true"
        hostFromEnv: RABBITMQ_URL