# Mangalodon Helm Chart Values

serviceAccount:
  create: false
  annotations: {}

imagePullSecrets:
  - name: ecr-registry-secret

images:
  repository: ""

frontend:
  name: frontend
  image:
    repository: 741448960615.dkr.ecr.ap-southeast-1.amazonaws.com/mangalodon/frontend
    tag: 0.0.1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: false
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

apiservice:
  name: apiservice
  image:
    repository: 741448960615.dkr.ecr.ap-southeast-1.amazonaws.com/mangalodon/apiservice
    tag: 0.0.1
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  autoscaling:
    enabled: false
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

scrapeservice:
  name: scrapeservice
  image:
    repository: 741448960615.dkr.ecr.ap-southeast-1.amazonaws.com/mangalodon/scrapeservice
    tag: 0.0.1
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

ingress:
  classname: cilium
  host: ""
  annotations: {}
  tls: []

postgres:
  name: postgres
  username: app
  vaultSecretPath: kv/mangalodon/dev/postgres
  schema: public
  version: 18
  instanceCount: 3
  extensions:
    pgvector: true
  storageSize: 5Gi

vault:
  server: https://192.168.1.10:8200
  path: kv
  version: v2
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZIVENDQXdXZ0F3SUJBZ0lVZDZuZ2prV1dRd2ZHYlFrbDFnZ2QwNm91TytRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hqRWNNQm9HQTFVRUF3d1RkbUYxYkhRdGNtOXZkQzFqWVM1c2IyTmhiREFlRncweU5qQTRNVGt4TkRNdwpNakZhRncwek5qQTRNVFl4TkRNd01qRmFNQjR4SERBYUJnTlZCQU1NRTNaaGRXeDBMWEp2YjNRdFkyRXViRzlqCllXd3dnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDa1RkOStEVHZyNjFLRVBDa3EKd0MvRTlEWU8zbFpKV3h3enFzK05JUXh6QktDaE9aOGk4OGJWcW9BeEpNZFNrWUQ5a1FMNU5DYkxzNUxUektOaAo2UjlZQmgvaHJZWEJlVEYyaW40MUNLeWVmbEVKL3FHRDhaOThFV2tiYjdqM3U3Y204ZXdIODkwOUhxN0xVUWVOCmg5bDlTWkdrem1aa0dmVVUyY014bEdwNnUrRjI3ZWFJRmlLVWNJVndVdFhyNFR2dXRydE1oTFV3eWlOL09sQU0KTjRBTHMxMU5uSUg2bEo4b0ppbFhpTS9YQnNiRzNGNTBtc0JmZVZYL29OaFdjS3RpTHF5WFUydE03UGsyS1NYZwpvb3pBcVFyM0N2QXErRTNqN2w2b2VkWlhRUjlJQkdITEllQnlVQVRUb0Jqa3BFWXVCV24wbHZkT2lXTUxEM2ZFCjFOOU9nSzBNbk8rRGUrekpJWWdsQXFjdWo2eVBMME12ZHpVQXFLaVpUcmtFZjBXejFxcUh1WUhEZ0R2WmxUbm4KL1RrVDlDQ3V4ckdVNHJ5azg4Z1EvaGFVQmsxT1ptRXlLRDcxci9nOFZkR0hrQ1d6MFgrR3Zka1BsSUh3UzJiVApGOFhMUW55QjBPaHRTamhtajhhVS9qT0JQdENGcTNReUJBZzZHU0JuVDFtMS9wdk0vSFlRa0JocjkrZWNtVnpvCnl4cDV2NjZwUFZVRWVZcnUzeTZnSFUyOFdZOXdGSWlsTVdPZjVWTXdGMVlHc2tvZG5iNS90dTZVUllNd0tLdTQKYjdlZ2tYK016d3VkQTBCK0VHODZoQWZ2dVgwMTF2eUo2ME1KZE1ZV2NuZHBObk9XRWc5RjNsMXY0aE8rTzhGagpmcElDUEt1bUNnNE03Mkk5OG5EYzNBa1pqd0lEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVcW02Z20xV2t2RWdiCmVMeko5NWN4QVFIR2VqUXdId1lEVlIwakJCZ3dGb0FVcW02Z20xV2t2RWdiZUx6Sjk1Y3hBUUhHZWpRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFpdzhreEtRRks5dUtxb3hzWXlGVgpTajR0TVo1ZktkZVp2SzZUS2xlaGRaNWhhMG45MFVWTzgvZHZjcXB1UWE3TjJSWjlxOCt6ckRjWDI0K2ZReFJLCmZQbTRuZXo2bE90VjJBN09jMGt6STg4d0dQWjRScVEzNjAwdGo5Mko5a0FWendaVzZYMXJRT01CTjdRd01RWVcKNm9xY2hPOXdxQ3daS3o4bU1VbUNqMUxoNXZNRjJ4MlNGcTVJZFIzbE54QituQ0twREl2KzM3VUxUZDIzeEZUagovcTdCT1lxa0RDMVUrN0hqMnVmM3RmYW5KdEpwN205MGxzRjZUNUVQRjBML000MEZKSzdXZFRRbkVpeld5bGxBClZIdWQzRFI2VitRa2NWaHgyanBqd2s5OTM3NlovSXRWcDRHaGkyYWg4cWUrTzhkUHVqbTUwUEZ5TzNrT1dlQi8KMjNMSzZQdmRseE1LcXpiTmNiSXN4THBQRDkwQWF4YndzcVkzV3p0MUg3a1ptYzBYNkhqZDNRZzhKL1c2MmhVYQpiVkFDWGlqV1pIQ3d0c0R0alN6VnVvUkExMmdPYk5jeFRLbkkwYTc3aFluUitLMWZVNDRJL3E2b2tiNzlVWFQ2CkF3bWl6a3loSTZMWms1ZVNrVHdPOUVrc0FLOVlJdTBkbnJLKyt3Ny9rSFdOMitiREhzcjNLemlPRWdlbnN0SDUKMkx3RGorQzh3TEd4WHk4WWFtRFI1TmJSTGRvK0d1b3JhZmhtcUxZSDFQNHNpbXhRa3ZLTm1SNU1MNzE0WDRXVAo4WFRvaC84SWJrQyt3QzErVlM4Nlg3K2cwUnJncUNGcUVlZ2RTRk91NEl1eDFkRkljaG9KQkM5TDlMWTZacGxuCmNWNkpLZlJyVmxMZHd5dTc3TnlPaldrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  kubernetesAuthMountPath: kubernetes
