apiVersion: v2
name: mangalodon
description: A Helm chart for Kubernetes for Mangalodon
type: application
version: 0.0.2
appVersion: "v0.0.2-alpha.1"

# TODO: add dependencies check before installing chart
# TODO: add network policy between pods/svcs

# dependencies:
#   - name: rabbitmq
#   - name: messaging-topology-operator
#   - name: cloudnative-pg
#     version: 0.29.0
#     repository: https://cloudnative-pg.github.io/charts
#   - name: vault
#     version: 0.34.1
#     repository: https://helm.releases.hashicorp.com
#   - name: vault-secrets-operator
#     version: 1.5.1
#     repository: https://helm.releases.hashicorp.com
#   - name: cert-manager
#     version: 1.21.1
#     repository: oci://quay.io/jetstack/charts/cert-manager
#   - name: keda
#     version: 2.20.2
#     repository: https://kedacore.github.io/charts
