BEGIN;
  CREATE SCHEMA IF NOT EXISTS ${schema};

  GRANT USAGE ON SCHEMA ${schema} TO ${app_user};
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${schema} TO ${app_user};
  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA ${schema} TO ${app_user};
  GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ${schema} TO ${app_user};

  ALTER DEFAULT PRIVILEGES FOR ROLE ${admin_user} IN SCHEMA ${schema} GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${app_user};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${admin_user} IN SCHEMA ${schema} GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${app_user};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${admin_user} IN SCHEMA ${schema} GRANT EXECUTE ON FUNCTIONS TO ${app_user};
COMMIT;