apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-secret-store
  namespace: {{ .Release.Namespace }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    external-secrets.io/ignore-maintenance-checks: "true"
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      version: {{ .Values.vault.version }}
      caBundle: {{ .Values.vault.caBundle }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.kubernetesAuthMountPath }}
          role: {{ .Release.Namespace }}
          serviceAccountRef:
            name: {{ .Chart.Name }}-secret-store
            namespace: {{ .Release.Namespace }}
